<?xml version="1.0" encoding="UTF-8" ?>


<!DOCTYPE sandwiches [
        <!ELEMENT sandwiches (ingridients|midlle|bottom)*>
        <!ELEMENT ingridients (top|midlle|bottom)*>
        <!ATTLIST ingridients
                name CDATA #REQUIRED>
        <!ELEMENT top (#PCDATA)>
        <!ATTLIST top
                sort CDATA #IMPLIED>
        <!ELEMENT midlle (#PCDATA)>
        <!ATTLIST midlle
                fresh CDATA #IMPLIED
                quantity CDATA #IMPLIED
                sort CDATA #IMPLIED>
        <!ELEMENT bottom (#PCDATA)>
        <!ATTLIST bottom
                sort CDATA #IMPLIED>
        ]>
<sandwiches>

    <ingridients name="taste_and_pretty">
        <top sort="white-normal">bread</top>
        <midlle sort="big-holes">cheese</midlle>
        <midlle sort="salami">sausage</midlle>
        <midlle quantity="3">salad</midlle>
        <bottom>pita</bottom>
    </ingridients>

    <ingridients name="tasteless_and_ugly">
        <midlle fresh="look_like">fish</midlle>
        <midlle quantity="15">cheese</midlle>
        <midlle quantity = "0">cucumber</midlle>
        <midlle sort="pepper_and_strawberry">mayonnaise</midlle>
        <bottom sort="black_and_blue">bread</bottom>
    </ingridients>


    <ingridients name="uncertain3000">
        <top>pita</top>
        <midlle fresh="100% new, was three days ago..." sort="look_like_salmon">fish</midlle>
        <bottom>bread</bottom>
    </ingridients>

    <!-- added by me -->
    <ingridients name="Krabsburger">
        <top>bread</top>
        <midlle quantity="1">cucumber</midlle>
        <midlle fresh="SPONGEBOB! How old this pattie is?">Craby pattie</midlle>
        <midlle sort="mustard">sauce</midlle>
        <midlle sort="mayo">sauce</midlle>
        <midlle sort="ketchup">sauce</midlle>
        <midlle quantity="3">onion</midlle>
        <midlle fresh="quite old">salad</midlle>
        <bottom>bread</bottom>
    </ingridients>



</sandwiches>